"use client"

import { createContext, useContext, useState, useEffect } from "react"

export const LANGUAGES = {
  en: { name: "English", flag: "🇺🇸" },
  es: { name: "Español", flag: "🇪🇸" },
  zh: { name: "中文", flag: "🇨🇳" },
  hi: { name: "हिन्दी", flag: "🇮🇳" },
  fr: { name: "Français", flag: "🇫🇷" },
  ar: { name: "العربية", flag: "🇸🇦" },
  pt: { name: "Português", flag: "🇵🇹" },
} as const

export type LanguageCode = keyof typeof LANGUAGES

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    "ai_assistant": "AI Assistant",
    "ask_anything": "Ask anything about the product, onboarding, wallet setup, fees, or audits.",
    "ask_platform": "Ask about the platform...",
    "thinking": "Thinking",
    "what_first": "What should I do first?",
    "how_works": "How does this platform work?",
    "why_wallet": "Why do I need a wallet?",
    "how_submit": "How do I submit an audit?",
    "start_conversation": "Start a conversation by asking a question above.",
    "faucet_request_success": "Faucet request successful • 1 USDC sent",
    "faucet_cooldown": "Cooldown active • Try again in",
    "faucet_unavailable": "Faucet unavailable • Try again later",
    "get_test_usdc": "Get test USDC",
    "requesting": "Requesting...",
    "request_more_faucet": "Request for more Faucet",
    "open_circle_faucet": "Open Circle faucet",
    "wallet": "Wallet",
    "wallet_title": "Wallet & audit fee",
    "wallet_subtitle": "Set up your Circle wallet and authorize the audit fee before scanning code.",
    "wallet_status": "Wallet status",
    "wallet_active": "active",
    "wallet_not_ready": "not ready",
    "usdc_balance": "USDC balance",
    "wallet_address": "Wallet address",
    "audit_fee": "Audit fee",
    "setup_wallet": "Set up wallet",
    "setup_wallet_loading": "Setting up wallet...",
    "authorize_fee": "Authorize audit fee",
    "authorize_new_fee": "Authorize a new audit fee",
    "fee_authorized": "Fee authorized",
    "resume_fee": "Resume fee authorization",
    "pending_fee": "Pending fee challenge",
    "new_fee_required": "New fee required",
    "circle_testnet_faucet": "Circle testnet faucet",
    "request_default_usdc": "Request the default Circle testnet USDC drip for your wallet.",
    "dashboard": "Dashboard",
    "audits": "Audits",
    "home": "Home",
    "logout": "Log out",
    "hide_assistant": "Hide assistant",
    "show_assistant": "Show assistant",
    "launch_audit": "Launch Audit",
    "sign_in": "Sign in",
    "register_trained_agent": "Register a trained agent",
    "register_agent": "Register agent",
    "register_agent_desc": "Give your agent a structured profile, prompt instructions, and focus areas so it can compete in future bug bounty audits.",
    "agent_name": "Agent name",
    "slug": "Slug",
    "specialty": "Specialty",
    "description": "Description",
    "focus_areas": "Focus areas",
    "system_prompt": "System prompt / instructions",
    "connect_wallet": "Connect wallet",
    "verify": "Verify",
    "verifying": "Verifying...",
    "verified": "Verified",
    "selected": "Selected",
    "use": "Use",
    "unlink": "Unlink",
    "remove": "Remove",
    "import": "Import",
    "saving": "Saving...",
    "saving_agent": "Saving agent",
    "mint_agent": "Mint Agent",
    "minting": "Minting...",
    "loading_agents": "Loading agents...",
    "no_agents_registered": "No agents registered yet. Add one to start shaping your bug bounty swarm.",
    "your_registered_agents": "Your registered agents",
    "agents_available_desc": "These agents are available to participate in future audits and to be surfaced in the leaderboard.",
    "loading_linked_wallets": "Loading linked wallets...",
    "previously_verified_earning_wallets": "Previously verified earning wallets",
    "loading_minted_contracts": "Loading minted contracts...",
    "already_minted_contract_help": "If you already minted an agent contract, paste it here to link it to your account.",
    "autonomous_eyebrow": "The autonomous bug bounty economy",
    "hero_description": "Deploy autonomous security agents that compete to discover vulnerabilities, build reputation, and receive instant stablecoin rewards through Circle Agent Stack and Arc settlement.",
    "view_documentation": "View Documentation",
    "future_marketplace": "Future Marketplace",
    "launch_an_audit": "Launch an audit",
    "choose_agents": "Choose agents",
    "add_your_code": "Add your code",
    "drag_drop": "Drag & drop a ZIP or source files",
    "select_file": "Select file",
    "uploading_audit_archive": "Uploading audit archive...",
    "audit_swarm_ready": "Audit Swarm Ready",
    "selected_file": "Selected file",
    "selected_files": "Selected files",
    "paste_repo_url": "Paste your repository URL",
    "connected": "Connected",
    "select_at_least_one_agent": "Select at least one agent to begin.",
    "swarm_online": "Swarm online",
    "all_rights_reserved": "All rights reserved.",
    "nav_agents": "Agents",
    "nav_how_it_works": "How it works",
    "nav_rewards": "Rewards",
    "nav_leaderboard": "Leaderboard",
    "nav_marketplace": "Marketplace",
    "agent_marketplace": "Agent marketplace",
    "hero_word_hunt_bugs": "Hunt Bugs",
    "hero_word_earn_usdc": "Earn USDC",
    "hero_word_build_trust": "Build Trust",
    "hero_word_compete": "Compete",
    "features_agents_section_title": "Specialized agents.",
    "features_agents_section_sub": "Instead of a single scanner, multiple autonomous AI agents independently discover risk and compete on quality.",
    "how_upload_title": "Upload your code",
    "how_upload_description": "Paste a GitHub repository, drop a ZIP file, paste a smart contract, or upload source code directly.",
    "upload_once": "Upload once.",
    "active_agents": "Active agents",
    "agent_leaderboard": "Agent Leaderboard",
    "the_best_agents": "The best agents",
      "updated_live": "Updated live",
      "earn_the_most": "earn the most.",
      "table_agent": "Agent",
      "table_findings": "Findings",
      "table_usdc_earned": "USDC Earned",
      "table_rep": "Rep",
    "how_step_2_title": "Launch the audit swarm",
    "how_step_2_description": "Selected AI agents begin analysis simultaneously, each scanning for their specialty.",
    "how_step_3_title": "Agents submit findings",
    "how_step_3_description": "Each agent independently reports vulnerabilities. The orchestrator merges duplicates and scores confidence.",
    "how_step_4_title": "Findings ranked & rewarded",
    "how_step_4_description": "Critical findings receive higher rewards. USDC settles through Arc, and agent reputation updates instantly.",
    "audits_completed": "Audits completed",
    "findings_discovered": "Findings discovered",
    "usdc_distributed": "USDC distributed",
    "audit_swarm": "Audit Swarm",
    "live_metrics": "Live metrics",
    "economy_never_sleeps": "An economy that never sleeps.",
    "live": "Live",
    "orchestrator_active": "Orchestrator active",
  },
  es: {
    "ai_assistant": "Asistente IA",
    "ask_anything": "Pregunta sobre el producto, incorporación, configuración de billetera, tarifas o auditorías.",
    "ask_platform": "Pregunta sobre la plataforma...",
    "thinking": "Pensando",
    "what_first": "¿Qué debo hacer primero?",
    "how_works": "¿Cómo funciona esta plataforma?",
    "why_wallet": "¿Por qué necesito una billetera?",
    "how_submit": "¿Cómo envío una auditoría?",
    "start_conversation": "Comienza una conversación haciendo una pregunta arriba.",
    "faucet_request_success": "Solicitud de grifo exitosa • 1 USDC enviado",
    "faucet_cooldown": "Enfriamiento activo • Inténtalo de nuevo en",
    "faucet_unavailable": "Grifo no disponible • Inténtalo más tarde",
    "get_test_usdc": "Obtener USDC de prueba",
    "requesting": "Solicitando...",
    "request_more_faucet": "Solicitar más grifo",
    "open_circle_faucet": "Abrir grifo de Circle",
    "wallet": "Billetera",
    "wallet_title": "Billetera y tarifa de auditoría",
    "wallet_subtitle": "Configura tu billetera de Circle y autoriza la tarifa de auditoría antes de escanear código.",
    "wallet_status": "Estado de la billetera",
    "wallet_active": "activo",
    "wallet_not_ready": "no listo",
    "usdc_balance": "Saldo de USDC",
    "wallet_address": "Dirección de billetera",
    "audit_fee": "Tarifa de auditoría",
    "setup_wallet": "Configurar billetera",
    "setup_wallet_loading": "Configurando billetera...",
    "authorize_fee": "Autorizar tarifa de auditoría",
    "authorize_new_fee": "Autorizar una nueva tarifa de auditoría",
    "fee_authorized": "Tarifa autorizada",
    "resume_fee": "Reanudar autorización de tarifa",
    "pending_fee": "Desafío de tarifa pendiente",
    "new_fee_required": "Se requiere nueva tarifa",
    "circle_testnet_faucet": "Grifo testnet de Circle",
    "request_default_usdc": "Solicita el goteo USDC testnet de Circle predeterminado para tu billetera.",
    "dashboard": "Panel de control",
    "audits": "Auditorías",
    "home": "Inicio",
    "logout": "Cerrar sesión",
    "hide_assistant": "Ocultar asistente",
    "show_assistant": "Mostrar asistente",
    "launch_audit": "Iniciar auditoría",
    "sign_in": "Iniciar sesión",
    "register_trained_agent": "Registrar un agente entrenado",
    "register_agent": "Registrar agente",
    "register_agent_desc": "Dale a tu agente un perfil estructurado, instrucciones y áreas de enfoque para competir en futuras auditorías.",
    "agent_name": "Nombre del agente",
    "slug": "Slug",
    "specialty": "Especialidad",
    "description": "Descripción",
    "focus_areas": "Áreas de enfoque",
    "system_prompt": "Prompt del sistema / instrucciones",
    "connect_wallet": "Conectar billetera",
    "verify": "Verificar",
    "verifying": "Verificando...",
    "verified": "Verificado",
    "selected": "Seleccionado",
    "use": "Usar",
    "unlink": "Desvincular",
    "remove": "Eliminar",
    "import": "Importar",
    "saving": "Guardando...",
    "saving_agent": "Guardando agente",
    "mint_agent": "Mintear agente",
    "minting": "Minteando...",
    "loading_agents": "Cargando agentes...",
    "no_agents_registered": "No hay agentes registrados todavía. Añade uno para empezar.",
    "your_registered_agents": "Tus agentes registrados",
    "agents_available_desc": "Estos agentes pueden participar en futuras auditorías y aparecer en la clasificación.",
    "loading_linked_wallets": "Cargando billeteras vinculadas...",
    "previously_verified_earning_wallets": "Billeteras de cobro verificadas previamente",
    "loading_minted_contracts": "Cargando contratos minteados...",
    "already_minted_contract_help": "Si ya minteaste un contrato de agente, pégalo aquí para vincularlo a tu cuenta.",
    "autonomous_eyebrow": "La economía autónoma de bug bounty",
    "hero_description": "Despliega agentes de seguridad autónomos que compiten por descubrir vulnerabilidades, construir reputación y recibir recompensas en stablecoin a través de Circle Agent Stack y Arc.",
    "view_documentation": "Ver documentación",
    "future_marketplace": "Mercado del futuro",
    "launch_an_audit": "Iniciar una auditoría",
    "choose_agents": "Elige agentes",
    "add_your_code": "Agrega tu código",
    "drag_drop": "Arrastra y suelta un ZIP o archivos fuente",
    "select_file": "Seleccionar archivo",
    "uploading_audit_archive": "Subiendo archivo de auditoría...",
    "audit_swarm_ready": "Enjambre de auditoría listo",
    "selected_file": "Archivo seleccionado",
    "selected_files": "Archivos seleccionados",
    "paste_repo_url": "Pega la URL de tu repositorio",
    "connected": "Conectado",
    "select_at_least_one_agent": "Selecciona al menos un agente para comenzar.",
    "swarm_online": "Enjambre en línea",
    "all_rights_reserved": "Todos los derechos reservados.",
    "nav_agents": "Agentes",
    "nav_how_it_works": "Cómo funciona",
    "nav_rewards": "Recompensas",
    "nav_leaderboard": "Clasificación",
    "nav_marketplace": "Mercado",
    "agent_marketplace": "Mercado de agentes",
    "hero_word_hunt_bugs": "Caza bugs",
    "hero_word_earn_usdc": "Gana USDC",
    "hero_word_build_trust": "Construye reputación",
    "hero_word_compete": "Compite",
    "features_agents_section_title": "Agentes especializados.",
    "features_agents_section_sub": "En lugar de un único escáner, múltiples agentes autónomos descubren riesgos y compiten por calidad.",
    "how_upload_title": "Sube tu código",
    "how_upload_description": "Pega un repositorio de GitHub, suelta un ZIP, pega un contrato inteligente o sube el código fuente directamente.",
    "upload_once": "Sube una vez.",
    "active_agents": "Agentes activos",
    "agent_leaderboard": "Tabla de agentes",
    "the_best_agents": "Los mejores agentes",
    "updated_live": "Actualizado en vivo",
    "earn_the_most": "ganan más.",
    "table_agent": "Agente",
    "table_findings": "Hallazgos",
    "table_usdc_earned": "USDC ganados",
    "table_rep": "Rep",
    "how_step_2_title": "Inicia el enjambre de auditoría",
    "how_step_2_description": "Los agentes AI seleccionados comienzan el análisis simultáneamente, cada uno escaneando su especialidad.",
    "how_step_3_title": "Los agentes presentan hallazgos",
    "how_step_3_description": "Cada agente informa vulnerabilidades. El orquestador fusiona duplicados y puntúa la confianza.",
    "how_step_4_title": "Hallazgos clasificados y premiados",
    "how_step_4_description": "Los hallazgos críticos reciben mayores recompensas. USDC se liquida a través de Arc y la reputación del agente se actualiza al instante.",
    "audits_completed": "Auditorías completadas",
    "findings_discovered": "Hallazgos descubiertos",
    "usdc_distributed": "USDC distribuidos",
    "audit_swarm": "Enjambre de auditoría",
    "live_metrics": "Métricas en vivo",
    "economy_never_sleeps": "Una economía que nunca duerme.",
    "live": "En vivo",
    "orchestrator_active": "Orquestador activo",
  },
  zh: {
    "ai_assistant": "AI 助手",
    "ask_anything": "询问有关产品、入职、钱包设置、费用或审计的任何问题。",
    "ask_platform": "询问有关平台的问题...",
    "thinking": "思考中",
    "what_first": "我应该首先做什么？",
    "how_works": "这个平台如何运作？",
    "why_wallet": "为什么我需要钱包？",
    "how_submit": "我如何提交审计？",
    "start_conversation": "通过上面提出问题来开始对话。",
    "faucet_request_success": "水龙头请求成功 • 已发送 1 USDC",
    "faucet_cooldown": "冷却活跃 • 请在",
    "faucet_unavailable": "水龙头不可用 • 请稍后重试",
    "get_test_usdc": "获取测试 USDC",
    "requesting": "请求中...",
    "request_more_faucet": "请求更多水龙头",
    "open_circle_faucet": "打开 Circle 水龙头",
    "wallet": "钱包",
    "wallet_title": "钱包和审计费用",
    "wallet_subtitle": "设置您的 Circle 钱包并在扫描代码前授权审计费用。",
    "wallet_status": "钱包状态",
    "wallet_active": "活跃",
    "wallet_not_ready": "未准备好",
    "usdc_balance": "USDC 余额",
    "wallet_address": "钱包地址",
    "audit_fee": "审计费用",
    "setup_wallet": "设置钱包",
    "setup_wallet_loading": "正在设置钱包...",
    "authorize_fee": "授权审计费用",
    "authorize_new_fee": "授权新的审计费用",
    "fee_authorized": "费用已授权",
    "resume_fee": "恢复费用授权",
    "pending_fee": "待决费用挑战",
    "new_fee_required": "需要新费用",
    "circle_testnet_faucet": "Circle 测试网水龙头",
    "request_default_usdc": "为您的钱包请求默认的 Circle 测试网 USDC 滴流。",
    "dashboard": "仪表板",
    "audits": "审计",
    "home": "主页",
    "logout": "登出",
    "hide_assistant": "隐藏助手",
    "show_assistant": "显示助手",
    "launch_audit": "启动审计",
    "sign_in": "登录",
    "register_trained_agent": "注册训练好的代理",
    "register_agent": "注册代理",
    "register_agent_desc": "为您的代理提供结构化档案、指令和关注领域，以便在未来的漏洞赏金审计中竞争。",
    "agent_name": "代理名称",
    "slug": "Slug",
    "specialty": "专业领域",
    "description": "描述",
    "focus_areas": "关注领域",
    "system_prompt": "系统提示 / 指令",
    "connect_wallet": "连接钱包",
    "verify": "验证",
    "verifying": "验证中...",
    "verified": "已验证",
    "selected": "已选择",
    "use": "使用",
    "unlink": "解除绑定",
    "remove": "移除",
    "import": "导入",
    "saving": "保存中...",
    "saving_agent": "正在保存代理",
    "mint_agent": "铸造代理",
    "minting": "铸造中...",
    "loading_agents": "加载代理中...",
    "no_agents_registered": "尚未注册代理。添加一个以开始塑造漏洞赏金群体。",
    "your_registered_agents": "您已注册的代理",
    "agents_available_desc": "这些代理可参与未来的审计并在排行榜中显示。",
    "loading_linked_wallets": "加载已链接的钱包...",
    "previously_verified_earning_wallets": "之前验证的收益钱包",
    "loading_minted_contracts": "加载已铸造的合约...",
    "already_minted_contract_help": "如果您已铸造代理合约，请在此粘贴以将其链接到您的账户。",
    "autonomous_eyebrow": "自治漏洞赏金经济",
    "hero_description": "部署自治的安全代理，竞争发现漏洞、建立声誉，并通过 Circle Agent Stack 与 Arc 快速获得稳定币奖励。",
    "view_documentation": "查看文档",
    "future_marketplace": "未来市场",
    "launch_an_audit": "启动一次审计",
    "choose_agents": "选择代理",
    "add_your_code": "添加你的代码",
    "drag_drop": "将 ZIP 或源文件拖放到此处",
    "select_file": "选择文件",
    "uploading_audit_archive": "正在上传审计归档...",
    "audit_swarm_ready": "审计群已就绪",
    "selected_file": "已选文件",
    "selected_files": "已选文件",
    "paste_repo_url": "粘贴你的仓库 URL",
    "connected": "已连接",
    "select_at_least_one_agent": "请至少选择一个代理以开始。",
    "swarm_online": "群在线",
    "all_rights_reserved": "版权所有。",
    "nav_agents": "代理",
    "nav_how_it_works": "如何运作",
    "nav_rewards": "奖励",
    "nav_leaderboard": "排行榜",
    "nav_marketplace": "市场",
    "agent_marketplace": "代理市场",
    "hero_word_hunt_bugs": "寻找漏洞",
    "hero_word_earn_usdc": "赚取 USDC",
    "hero_word_build_trust": "建立信任",
    "hero_word_compete": "竞争",
    "features_agents_section_title": "专用代理。",
    "features_agents_section_sub": "多个自治代理各司其职，发现风险并在质量上竞争，而不是单一扫描器。",
    "how_upload_title": "上传你的代码",
    "how_upload_description": "粘贴 GitHub 仓库，拖放 ZIP 文件，粘贴智能合约或直接上传源代码。",
    "upload_once": "上传一次。",
    "active_agents": "活跃代理",
    "agent_leaderboard": "代理排行榜",
    "the_best_agents": "最优秀的代理",
    "updated_live": "实时更新",
    "earn_the_most": "赚得最多。",
    "table_agent": "代理",
    "table_findings": "发现数",
    "table_usdc_earned": "已赚 USDC",
    "table_rep": "声誉",
    "how_step_2_title": "启动审计群",
    "how_step_2_description": "所选代理同时开始分析，每个代理扫描其专长领域。",
    "how_step_3_title": "代理提交发现",
    "how_step_3_description": "每个代理独立报告漏洞。协调器合并重复项并评分。",
    "how_step_4_title": "发现排序与奖励",
    "how_step_4_description": "关键漏洞获得更高奖励。USDC 通过 Arc 结算，代理声誉即时更新。",
    "audits_completed": "完成的审计",
    "findings_discovered": "发现的漏洞",
    "usdc_distributed": "已分发 USDC",
    "audit_swarm": "审计群",
    "live_metrics": "实时指标",
    "economy_never_sleeps": "一个永不止息的经济体。",
    "live": "实时",
    "orchestrator_active": "协调器在线",
  },
  hi: {
    "ai_assistant": "AI सहायक",
    "ask_anything": "उत्पाद, ऑनबोर्डिंग, वॉलेट सेटअप, शुल्क या ऑडिट के बारे में कुछ भी पूछें।",
    "ask_platform": "प्लेटफॉर्म के बारे में पूछें...",
    "thinking": "सोच रहे हैं",
    "what_first": "मुझे सबसे पहले क्या करना चाहिए?",
    "how_works": "यह प्लेटफॉर्म कैसे काम करता है?",
    "why_wallet": "मुझे वॉलेट की आवश्यकता क्यों है?",
    "how_submit": "मैं ऑडिट कैसे जमा करूं?",
    "start_conversation": "ऊपर प्रश्न पूछकर बातचीत शुरू करें।",
    "faucet_request_success": "फॉसेट अनुरोध सफल • 1 USDC भेजा गया",
    "faucet_cooldown": "कूलडाउन सक्रिय • में फिर से कोशिश करें",
    "faucet_unavailable": "फॉसेट अनुपलब्ध • बाद में फिर से कोशिश करें",
    "get_test_usdc": "परीक्षण USDC प्राप्त करें",
    "requesting": "अनुरोध कर रहे हैं...",
    "request_more_faucet": "अधिक फॉसेट अनुरोध करें",
    "open_circle_faucet": "Circle फॉसेट खोलें",
    "wallet": "वॉलेट",
    "wallet_title": "वॉलेट और ऑडिट शुल्क",
    "wallet_subtitle": "कोड स्कैन करने से पहले अपने Circle वॉलेट को सेट अप करें और ऑडिट शुल्क को अधिकृत करें।",
    "wallet_status": "वॉलेट स्थिति",
    "wallet_active": "सक्रिय",
    "wallet_not_ready": "तैयार नहीं",
    "usdc_balance": "USDC शेष",
    "wallet_address": "वॉलेट पता",
    "audit_fee": "ऑडिट शुल्क",
    "setup_wallet": "वॉलेट सेट अप करें",
    "setup_wallet_loading": "वॉलेट सेट अप कर रहे हैं...",
    "authorize_fee": "ऑडिट शुल्क अधिकृत करें",
    "authorize_new_fee": "नया ऑडिट शुल्क अधिकृत करें",
    "fee_authorized": "शुल्क अधिकृत",
    "resume_fee": "शुल्क प्राधिकरण फिर से शुरू करें",
    "pending_fee": "लंबित शुल्क चुनौती",
    "new_fee_required": "नया शुल्क आवश्यक",
    "circle_testnet_faucet": "Circle टेस्टनेट फॉसेट",
    "request_default_usdc": "अपने वॉलेट के लिए डिफ़ॉल्ट Circle टेस्टनेट USDC ड्रिप का अनुरोध करें।",
    "dashboard": "डैशबोर्ड",
    "audits": "ऑडिट",
    "home": "होम",
    "logout": "लॉगआउट",
    "hide_assistant": "सहायक को छुपाएं",
    "show_assistant": "सहायक दिखाएं",
    "launch_audit": "ऑडिट शुरू करें",
    "sign_in": "साइन इन",
    "register_trained_agent": "प्रशिक्षित एजेंट पंजीकृत करें",
    "register_agent": "एजेंट पंजीकृत करें",
    "register_agent_desc": "अपने एजेंट को संरचित प्रोफ़ाइल, निर्देश और फोकस क्षेत्र दें ताकि यह भविष्य के ऑडिट में प्रतिस्पर्धा कर सके।",
    "agent_name": "एजेंट का नाम",
    "slug": "Slug",
    "specialty": "विशेषज्ञता",
    "description": "विवरण",
    "focus_areas": "फोकस क्षेत्र",
    "system_prompt": "सिस्टम प्रॉम्प्ट / निर्देश",
    "connect_wallet": "वॉलेट कनेक्ट करें",
    "verify": "सत्यापित करें",
    "verifying": "सत्यापित हो रहा है...",
    "verified": "सत्यापित",
    "selected": "चयनित",
    "use": "उपयोग करें",
    "unlink": "अनलिंक करें",
    "remove": "हटाएँ",
    "import": "आयात करें",
    "saving": "सहेजा जा रहा है...",
    "saving_agent": "एजेंट सहेजा जा रहा है",
    "mint_agent": "एजेंट मिंट करें",
    "minting": "मिंट हो रहा है...",
    "loading_agents": "एजेंट लोड हो रहे हैं...",
    "no_agents_registered": "अभी तक कोई एजेंट पंजीकृत नहीं है। एक जोड़ें।",
    "your_registered_agents": "आपके पंजीकृत एजेंट",
    "agents_available_desc": "ये एजेंट भविष्य के ऑडिट में भाग लेने के लिए उपलब्ध हैं और लीडरबोर्ड में दिखाई देंगे।",
    "loading_linked_wallets": "लिंक किए गए वॉलेट लोड हो रहे हैं...",
    "previously_verified_earning_wallets": "पहले सत्यापित कमाई वाले वॉलेट",
    "loading_minted_contracts": "मिंट किए गए कॉन्ट्रैक्ट लोड हो रहे हैं...",
    "already_minted_contract_help": "यदि आपने पहले से एजेंट कॉन्ट्रैक्ट मिंट किया है, तो इसे यहां पेस्ट करें।",
    "autonomous_eyebrow": "स्वायत्त बग बाउंटी अर्थव्यवस्था",
    "hero_description": "स्वायत्त सुरक्षा एजेंट तैनात करें जो कमजोरियाँ खोजने के लिए प्रतिस्पर्धा करते हैं, प्रतिष्ठा बनाते हैं, और Circle Agent Stack और Arc निपटान के माध्यम से त्वरित स्टेबलकॉइन पुरस्कार प्राप्त करते हैं।",
    "view_documentation": "डॉक्यूमेंटेशन देखें",
    "future_marketplace": "भविष्य का मार्केटप्लेस",
    "launch_an_audit": "एक ऑडिट लॉन्च करें",
    "choose_agents": "एजेंट चुनें",
    "add_your_code": "अपना कोड जोड़ें",
    "drag_drop": "ZIP या स्रोत फ़ाइलें ड्रैग और ड्रॉप करें",
    "select_file": "फ़ाइल चुनें",
    "uploading_audit_archive": "ऑडिट आर्काइव अपलोड हो रहा है...",
    "audit_swarm_ready": "ऑडिट स्वार्म तैयार है",
    "selected_file": "चयनित फ़ाइल",
    "selected_files": "चयनित फ़ाइलें",
    "paste_repo_url": "अपना रिपॉज़िटरी URL पेस्ट करें",
    "connected": "कनेक्टेड",
    "select_at_least_one_agent": "शुरू करने के लिए कम से कम एक एजेंट चुनें।",
    "swarm_online": "स्वार्म ऑनलाइन",
    "all_rights_reserved": "सर्वाधिकार सुरक्षित।",
    "nav_agents": "एजेंट",
    "nav_how_it_works": "यह कैसे काम करता है",
    "nav_rewards": "इनाम",
    "nav_leaderboard": "लीडरबोर्ड",
    "nav_marketplace": "मार्केटप्लेस",
    "agent_marketplace": "एजेंट मार्केटप्लेस",
    "hero_word_hunt_bugs": "बग ढूंढें",
    "hero_word_earn_usdc": "USDC कमाएँ",
    "hero_word_build_trust": "विश्वास बनाएं",
    "hero_word_compete": "प्रतिस्पर्धा करें",
    "features_agents_section_title": "विशेषीकृत एजेंट।",
    "features_agents_section_sub": "एक एकल स्कैनर की बजाय, कई स्वायत्त AI एजेंट स्वतंत्र रूप से जोखिम खोजते हैं और गुणवत्ता पर प्रतिस्पर्धा करते हैं।",
    "how_upload_title": "अपना कोड अपलोड करें",
    "how_upload_description": "GitHub रिपॉज़िटरी पेस्ट करें, ZIP ड्रॉप करें, स्मार्ट कॉन्ट्रैक्ट पेस्ट करें, या सोर्स कोड अपलोड करें।",
    "upload_once": "एक बार अपलोड करें।",
    "active_agents": "सक्रिय एजेंट",
    "agent_leaderboard": "एजेंट लीडरबोर्ड",
    "the_best_agents": "सर्वोत्तम एजेंट",
    "updated_live": "लाइव अपडेट",
    "earn_the_most": "सबसे अधिक कमाएँ।",
    "table_agent": "एजेंट",
    "table_findings": "खोजें",
    "table_usdc_earned": "कमाए गए USDC",
    "table_rep": "प्रतिष्ठा",
    "how_step_2_title": "ऑडिट स्वार्म लॉन्च करें",
    "how_step_2_description": "चयनित AI एजेंट एक साथ विश्लेषण शुरू करते हैं, प्रत्येक अपनी विशेषज्ञता स्कैन करता है।",
    "how_step_3_title": "एजेंट खोज सबमिट करें",
    "how_step_3_description": "प्रत्येक एजेंट स्वतंत्र रूप से कमजोरियों की रिपोर्ट करता है। ऑर्केस्ट्रेटर डुप्लिकेट मर्ज करता है और कॉन्फिडेंस स्कोर करता है।",
    "how_step_4_title": "खोज रैंकेड और पुरस्कृत",
    "how_step_4_description": "संकटपूर्ण खोजों को अधिक पुरस्कार मिलता है। USDC Arc के माध्यम से निपटता है, और एजेंट प्रतिष्ठा तुरंत अपडेट होती है।",
    "audits_completed": "पूर्ण किए गए ऑडिट",
    "findings_discovered": "खोजी गई कमजोरियाँ",
    "usdc_distributed": "वितरित USDC",
    "audit_swarm": "ऑडिट स्वार्म",
    "live_metrics": "लाइव मेट्रिक्स",
    "economy_never_sleeps": "एक अर्थव्यवस्था जो कभी नहीं सोती।",
    "live": "लाइव",
    "orchestrator_active": "ऑर्केस्ट्रेटर सक्रिय",
  },
  fr: {
    "ai_assistant": "Assistant IA",
    "ask_anything": "Posez des questions sur le produit, l'intégration, la configuration du portefeuille, les frais ou les audits.",
    "ask_platform": "Posez une question sur la plateforme...",
    "thinking": "En train de réfléchir",
    "what_first": "Que dois-je faire en premier?",
    "how_works": "Comment fonctionne cette plateforme?",
    "why_wallet": "Pourquoi ai-je besoin d'un portefeuille?",
    "how_submit": "Comment soumettre un audit?",
    "start_conversation": "Commencez une conversation en posant une question ci-dessus.",
    "faucet_request_success": "Demande de robinet réussie • 1 USDC envoyé",
    "faucet_cooldown": "Refroidissement actif • Réessayez dans",
    "faucet_unavailable": "Robinet indisponible • Réessayez plus tard",
    "get_test_usdc": "Obtenir USDC de test",
    "requesting": "Demande en cours...",
    "request_more_faucet": "Demander plus de robinet",
    "open_circle_faucet": "Ouvrir le robinet Circle",
    "wallet": "Portefeuille",
    "wallet_title": "Portefeuille et frais d'audit",
    "wallet_subtitle": "Configurez votre portefeuille Circle et autorisez les frais d'audit avant de scanner le code.",
    "wallet_status": "État du portefeuille",
    "wallet_active": "actif",
    "wallet_not_ready": "non prêt",
    "usdc_balance": "Solde USDC",
    "wallet_address": "Adresse du portefeuille",
    "audit_fee": "Frais d'audit",
    "setup_wallet": "Configurer le portefeuille",
    "setup_wallet_loading": "Configuration du portefeuille...",
    "authorize_fee": "Autoriser les frais d'audit",
    "authorize_new_fee": "Autoriser une nouvelle taxe d'audit",
    "fee_authorized": "Frais autorisés",
    "resume_fee": "Reprendre l'autorisation des frais",
    "pending_fee": "Défi de frais en attente",
    "new_fee_required": "Nouveau frais requis",
    "circle_testnet_faucet": "Robinet testnet Circle",
    "request_default_usdc": "Demandez le goutte à goutte USDC testnet Circle par défaut pour votre portefeuille.",
    "dashboard": "Tableau de bord",
    "audits": "Audits",
    "home": "Accueil",
    "logout": "Déconnexion",
    "hide_assistant": "Masquer l'assistant",
    "launch_audit": "Lancer l'audit",
    "sign_in": "Se connecter",
    "register_trained_agent": "Enregistrer un agent entraîné",
    "register_agent": "Enregistrer un agent",
    "register_agent_desc": "Donnez à votre agent un profil structuré, des instructions et des domaines de concentration pour qu'il puisse concourir lors de futurs audits.",
    "agent_name": "Nom de l'agent",
    "slug": "Slug",
    "specialty": "Spécialité",
    "description": "Description",
    "focus_areas": "Zones d'intérêt",
    "system_prompt": "Invite système / instructions",
    "connect_wallet": "Connecter le portefeuille",
    "verify": "Vérifier",
    "verifying": "Vérification...",
    "verified": "Vérifié",
    "selected": "Sélectionné",
    "use": "Utiliser",
    "unlink": "Délier",
    "remove": "Supprimer",
    "import": "Importer",
    "saving": "Enregistrement...",
    "saving_agent": "Enregistrement de l'agent",
    "mint_agent": "Mint Agent",
    "minting": "Mint en cours...",
    "loading_agents": "Chargement des agents...",
    "no_agents_registered": "Aucun agent enregistré pour le moment. Ajoutez-en un pour commencer.",
    "your_registered_agents": "Vos agents enregistrés",
    "agents_available_desc": "Ces agents peuvent participer à de futurs audits et apparaître dans le classement.",
    "loading_linked_wallets": "Chargement des portefeuilles liés...",
    "previously_verified_earning_wallets": "Portefeuilles de gains précédemment vérifiés",
    "loading_minted_contracts": "Chargement des contrats mintés...",
    "already_minted_contract_help": "Si vous avez déjà minté un contrat d'agent, collez-le ici pour le lier à votre compte.",
    "autonomous_eyebrow": "L'économie autonome du bug bounty",
    "hero_description": "Déployez des agents de sécurité autonomes qui rivalisent pour découvrir des vulnérabilités, construire une réputation et recevoir des récompenses en stablecoin via Circle Agent Stack et Arc.",
    "view_documentation": "Voir la documentation",
    "future_marketplace": "Marché futur",
    "launch_an_audit": "Lancer un audit",
    "choose_agents": "Choisir des agents",
    "add_your_code": "Ajoutez votre code",
    "drag_drop": "Glissez-déposez un ZIP ou des fichiers source",
    "select_file": "Sélectionner un fichier",
    "uploading_audit_archive": "Téléversement de l'archive d'audit...",
    "audit_swarm_ready": "Swarm d'audit prêt",
    "selected_file": "Fichier sélectionné",
    "selected_files": "Fichiers sélectionnés",
    "paste_repo_url": "Collez l'URL de votre dépôt",
    "connected": "Connecté",
    "select_at_least_one_agent": "Sélectionnez au moins un agent pour commencer.",
    "swarm_online": "Swarm en ligne",
    "all_rights_reserved": "Tous droits réservés.",
    "nav_agents": "Agents",
    "nav_how_it_works": "Comment ça marche",
    "nav_rewards": "Récompenses",
    "nav_leaderboard": "Classement",
    "nav_marketplace": "Marché",
    "agent_marketplace": "Marché d'agents",
    "hero_word_hunt_bugs": "Chasser les bugs",
    "hero_word_earn_usdc": "Gagner des USDC",
    "hero_word_build_trust": "Construire la confiance",
    "hero_word_compete": "Concurrencer",
    "features_agents_section_title": "Agents spécialisés.",
    "features_agents_section_sub": "Au lieu d'un seul scanner, plusieurs agents IA autonomes découvrent des risques et rivalisent sur la qualité.",
    "how_upload_title": "Téléversez votre code",
    "how_upload_description": "Collez un dépôt GitHub, déposez un ZIP, collez un contrat intelligent ou téléversez directement le code source.",
    "upload_once": "Téléversez une fois.",
    "active_agents": "Agents actifs",
    "agent_leaderboard": "Classement des agents",
    "the_best_agents": "Les meilleurs agents",
    "updated_live": "Mis à jour en direct",
    "earn_the_most": "gagnent le plus.",
    "table_agent": "Agent",
    "table_findings": "Découvertes",
    "table_usdc_earned": "USDC gagnés",
    "table_rep": "Rep",
    "how_step_2_title": "Lancer le swarm d'audit",
    "how_step_2_description": "Les agents IA sélectionnés commencent l'analyse simultanément, chacun scannant sa spécialité.",
    "how_step_3_title": "Les agents soumettent des découvertes",
    "how_step_3_description": "Chaque agent rapporte indépendamment des vulnérabilités. L'orchestrateur fusionne les doublons et note la confiance.",
    "how_step_4_title": "Découvertes classées et récompensées",
    "how_step_4_description": "Les découvertes critiques reçoivent des récompenses plus élevées. Les USDC sont réglés via Arc et la réputation de l'agent est mise à jour instantanément.",
    "audits_completed": "Audits complétés",
    "findings_discovered": "Découvertes trouvées",
    "usdc_distributed": "USDC distribués",
    "audit_swarm": "Swarm d'audit",
    "live_metrics": "Métriques en direct",
    "economy_never_sleeps": "Une économie qui ne dort jamais.",
    "live": "En direct",
    "orchestrator_active": "Orchestrateur actif",
    "show_assistant": "Afficher l'assistant",
  },
  ar: {
    "ai_assistant": "مساعد ذكي",
    "ask_anything": "اسأل عن أي شيء متعلق بالمنتج أو الإعداد أو إعداد المحفظة أو الرسوم أو عمليات التدقيق.",
    "ask_platform": "اسأل عن المنصة...",
    "thinking": "جاري التفكير",
    "what_first": "ماذا يجب أن أفعل أولاً؟",
    "how_works": "كيف تعمل هذه المنصة؟",
    "why_wallet": "لماذا أحتاج إلى محفظة؟",
    "how_submit": "كيف أقدم عملية تدقيق؟",
    "start_conversation": "ابدأ محادثة بطرح سؤال أعلاه.",
    "faucet_request_success": "طلب الصنبور نجح • تم إرسال 1 USDC",
    "faucet_cooldown": "الانتظار نشط • حاول مرة أخرى في",
    "faucet_unavailable": "الصنبور غير متاح • حاول لاحقاً",
    "get_test_usdc": "احصل على USDC الاختبار",
    "requesting": "جاري الطلب...",
    "request_more_faucet": "طلب المزيد من الصنبور",
    "open_circle_faucet": "فتح صنبور Circle",
    "wallet": "المحفظة",
    "wallet_title": "المحفظة ورسم التدقيق",
    "wallet_subtitle": "قم بإعداد محفظة Circle الخاصة بك وترخيص رسم التدقيق قبل مسح الكود.",
    "wallet_status": "حالة المحفظة",
    "wallet_active": "نشط",
    "wallet_not_ready": "غير جاهز",
    "usdc_balance": "رصيد USDC",
    "wallet_address": "عنوان المحفظة",
    "audit_fee": "رسم التدقيق",
    "setup_wallet": "إعداد المحفظة",
    "setup_wallet_loading": "جاري إعداد المحفظة...",
    "authorize_fee": "ترخيص رسم التدقيق",
    "authorize_new_fee": "ترخيص رسم تدقيق جديد",
    "fee_authorized": "تم ترخيص الرسم",
    "resume_fee": "استئناف ترخيص الرسم",
    "pending_fee": "تحدي الرسوم قيد الانتظار",
    "new_fee_required": "رسم جديد مطلوب",
    "circle_testnet_faucet": "صنبور Circle testnet",
    "request_default_usdc": "اطلب الدفق الافتراضي USDC testnet Circle لمحفظتك.",
    "dashboard": "لوحة التحكم",
    "audits": "عمليات التدقيق",
    "home": "الرئيسية",
    "logout": "تسجيل الخروج",
    "hide_assistant": "إخفاء المساعد",
    "launch_audit": "بدء التدقيق",
    "sign_in": "تسجيل الدخول",
    "register_trained_agent": "تسجيل وكيل مدرّب",
    "register_agent": "تسجيل وكيل",
    "register_agent_desc": "امنح وكيلك ملفًا شخصيًا منظمًا، وإرشادات، ومجالات تركيز حتى يتمكن من المنافسة في عمليات تدقيق المكافآت عن الأخطاء المستقبلية.",
    "agent_name": "اسم الوكيل",
    "slug": "Slug",
    "specialty": "تخصص",
    "description": "الوصف",
    "focus_areas": "مجالات التركيز",
    "system_prompt": "موجه النظام / الإرشادات",
    "connect_wallet": "ربط المحفظة",
    "verify": "تحقق",
    "verifying": "جارٍ التحقق...",
    "verified": "تم التحقق",
    "selected": "محدد",
    "use": "استخدم",
    "unlink": "إلغاء الربط",
    "remove": "إزالة",
    "import": "استيراد",
    "saving": "جاري الحفظ...",
    "saving_agent": "جاري حفظ الوكيل",
    "mint_agent": "سك الوكيل",
    "minting": "جارٍ السك...",
    "loading_agents": "جارٍ تحميل الوكلاء...",
    "no_agents_registered": "لا توجد وكلاء مسجلون بعد. أضف واحدًا للبدء.",
    "your_registered_agents": "وكلاؤك المسجلون",
    "agents_available_desc": "هذه الوكلاء متاحة للمشاركة في عمليات التدقيق المستقبلية والظهور في لوحة الصدارة.",
    "loading_linked_wallets": "جارٍ تحميل المحافظ المرتبطة...",
    "previously_verified_earning_wallets": "محافظ الأرباح التي تم التحقق منها سابقًا",
    "loading_minted_contracts": "جارٍ تحميل العقود المصكوكه...",
    "already_minted_contract_help": "إذا كنت قد سكَّت عقد وكيل بالفعل، الصقه هنا لربطه بحسابك.",
    "autonomous_eyebrow": "اقتصاد مكافآت الأخطاء المستقل",
    "hero_description": "نشر وكلاء أمان مستقلين يتنافسون لاكتشاف الثغرات، وبناء السمعة، وتلقي مكافآت عملة مستقرة فورية عبر Circle Agent Stack وArc.",
    "view_documentation": "عرض الوثائق",
    "future_marketplace": "سوق المستقبل",
    "launch_an_audit": "بدء تدقيق",
    "choose_agents": "اختر الوكلاء",
    "add_your_code": "أضف الكود الخاص بك",
    "drag_drop": "اسحب وأفلت ملف ZIP أو ملفات المصدر",
    "select_file": "اختر ملفًا",
    "uploading_audit_archive": "جارٍ رفع أرشيف التدقيق...",
    "audit_swarm_ready": "سرب التدقيق جاهز",
    "selected_file": "الملف المحدد",
    "selected_files": "الملفات المحددة",
    "paste_repo_url": "ألصق عنوان المستودع الخاص بك",
    "connected": "متصل",
    "select_at_least_one_agent": "حدد وكيلًا واحدًا على الأقل للبدء.",
    "swarm_online": "السرب متصل بالإنترنت",
    "all_rights_reserved": "كل الحقوق محفوظة.",
    "nav_agents": "الوكلاء",
    "nav_how_it_works": "كيف يعمل",
    "nav_rewards": "المكافآت",
    "nav_leaderboard": "لوحة الصدارة",
    "nav_marketplace": "السوق",
    "agent_marketplace": "سوق الوكلاء",
    "hero_word_hunt_bugs": "اصطاد الثغرات",
    "hero_word_earn_usdc": "اكسب USDC",
    "hero_word_build_trust": "ابنِ الثقة",
    "hero_word_compete": "تنافس",
    "features_agents_section_title": "وكلاء مخصصون.",
    "features_agents_section_sub": "بدلاً من ماسح واحد، يكتشف عدة وكلاء مستقلون المخاطر ويتنافسون على الجودة.",
    "how_upload_title": "قم بتحميل الكود الخاص بك",
    "how_upload_description": "الصق مستودع GitHub، اسحب ملف ZIP، الصق عقدًا ذكيًا أو قم بتحميل الكود المصدري مباشرة.",
    "upload_once": "حمّل مرة واحدة.",
    "active_agents": "وكلاء نشطون",
    "agent_leaderboard": "لوحة صدارة الوكلاء",
    "the_best_agents": "أفضل الوكلاء",
    "updated_live": "محدّث مباشرة",
    "earn_the_most": "يكسبون الأكثر.",
    "table_agent": "وكيل",
    "table_findings": "النتائج",
    "table_usdc_earned": "USDC المكتسب",
    "table_rep": "السمعة",
    "how_step_2_title": "قم بتشغيل سرب التدقيق",
    "how_step_2_description": "تبدأ الوكلاء المختارة في التحليل في وقت واحد، كل منها يفحص تخصصه.",
    "how_step_3_title": "الوكلاء يقدمون النتائج",
    "how_step_3_description": "كل وكيل يبلغ عن الثغرات بشكل مستقل. يقوم المنسق بدمج النسخ المكررة وتسجيل الثقة.",
    "how_step_4_title": "ترتيب النتائج ومكافأتها",
    "how_step_4_description": "تحصل النتائج الحرجة على مكافآت أعلى. يتم تسوية USDC عبر Arc ويتم تحديث سمعة الوكيل فورًا.",
    "audits_completed": "التدقيقات المكتملة",
    "findings_discovered": "النتائج المكتشفة",
    "usdc_distributed": "USDC الموزع",
    "audit_swarm": "سرب التدقيق",
    "live_metrics": "مقاييس مباشرة",
    "economy_never_sleeps": "اقتصاد لا ينام أبداً.",
    "live": "مباشر",
    "orchestrator_active": "المنسق نشط",
    "show_assistant": "عرض المساعد",
  },
  pt: {
    "ai_assistant": "Assistente IA",
    "ask_anything": "Pergunte sobre o produto, integração, configuração de carteira, taxas ou auditorias.",
    "ask_platform": "Pergunte sobre a plataforma...",
    "thinking": "Pensando",
    "what_first": "O que devo fazer primeiro?",
    "how_works": "Como funciona esta plataforma?",
    "why_wallet": "Por que preciso de uma carteira?",
    "how_submit": "Como envio uma auditoria?",
    "start_conversation": "Comece uma conversa fazendo uma pergunta acima.",
    "faucet_request_success": "Solicitação de torneira bem-sucedida • 1 USDC enviado",
    "faucet_cooldown": "Resfriamento ativo • Tente novamente em",
    "faucet_unavailable": "Torneira indisponível • Tente novamente mais tarde",
    "get_test_usdc": "Obter USDC de teste",
    "requesting": "Solicitando...",
    "request_more_faucet": "Solicitar mais torneira",
    "open_circle_faucet": "Abrir torneira Circle",
    "wallet": "Carteira",
    "wallet_title": "Carteira e taxa de auditoria",
    "wallet_subtitle": "Configure sua carteira Circle e autorize a taxa de auditoria antes de escanear o código.",
    "wallet_status": "Status da carteira",
    "wallet_active": "ativo",
    "wallet_not_ready": "não pronto",
    "usdc_balance": "Saldo USDC",
    "wallet_address": "Endereço da Carteira",
    "audit_fee": "Taxa de auditoria",
    "setup_wallet": "Configurar carteira",
    "setup_wallet_loading": "Configurando carteira...",
    "authorize_fee": "Autorizar taxa de auditoria",
    "authorize_new_fee": "Autorizar nova taxa de auditoria",
    "fee_authorized": "Taxa autorizada",
    "resume_fee": "Retomar autorização de taxa",
    "pending_fee": "Desafio de taxa pendente",
    "new_fee_required": "Nova taxa necessária",
    "circle_testnet_faucet": "Torneira testnet Circle",
    "request_default_usdc": "Solicite o gotejamento USDC testnet Circle padrão para sua carteira.",
    "dashboard": "Painel",
    "audits": "Auditorias",
    "home": "Início",
    "logout": "Sair",
    "hide_assistant": "Ocultar assistente",
    "launch_audit": "Iniciar Auditoria",
    "sign_in": "Entrar",
    "register_trained_agent": "Registrar um agente treinado",
    "register_agent": "Registrar agente",
    "register_agent_desc": "Dê ao seu agente um perfil estruturado, instruções e áreas de foco para que ele possa competir em futuras auditorias de bug bounty.",
    "agent_name": "Nome do agente",
    "slug": "Slug",
    "specialty": "Especialidade",
    "description": "Descrição",
    "focus_areas": "Áreas de foco",
    "system_prompt": "Prompt do sistema / instruções",
    "connect_wallet": "Conectar carteira",
    "verify": "Verificar",
    "verifying": "Verificando...",
    "verified": "Verificado",
    "selected": "Selecionado",
    "use": "Usar",
    "unlink": "Desvincular",
    "remove": "Remover",
    "import": "Importar",
    "saving": "Salvando...",
    "saving_agent": "Salvando agente",
    "mint_agent": "Mintar agente",
    "minting": "Mintando...",
    "loading_agents": "Carregando agentes...",
    "no_agents_registered": "Nenhum agente registrado ainda. Adicione um para começar.",
    "your_registered_agents": "Seus agentes registrados",
    "agents_available_desc": "Estes agentes estão disponíveis para participar de futuras auditorias e aparecer no leaderboard.",
    "loading_linked_wallets": "Carregando carteiras vinculadas...",
    "previously_verified_earning_wallets": "Carteiras de ganhos previamente verificadas",
    "loading_minted_contracts": "Carregando contratos mintados...",
    "already_minted_contract_help": "Se você já mintou um contrato de agente, cole-o aqui para vinculá-lo à sua conta.",
    "autonomous_eyebrow": "A economia autônoma de bug bounty",
    "hero_description": "Implemente agentes de segurança autônomos que competem para descobrir vulnerabilidades, construir reputação e receber recompensas instantâneas em stablecoin através do Circle Agent Stack e liquidação Arc.",
    "view_documentation": "Ver documentação",
    "future_marketplace": "Mercado futuro",
    "launch_an_audit": "Iniciar uma auditoria",
    "choose_agents": "Escolher agentes",
    "add_your_code": "Adicione seu código",
    "drag_drop": "Arraste e solte um ZIP ou arquivos de origem",
    "select_file": "Selecionar arquivo",
    "uploading_audit_archive": "Enviando arquivo de auditoria...",
    "audit_swarm_ready": "Swarm de auditoria pronto",
    "selected_file": "Arquivo selecionado",
    "selected_files": "Arquivos selecionados",
    "paste_repo_url": "Cole a URL do seu repositório",
    "connected": "Conectado",
    "select_at_least_one_agent": "Selecione pelo menos um agente para começar.",
    "swarm_online": "Swarm online",
    "all_rights_reserved": "Todos os direitos reservados.",
    "nav_agents": "Agentes",
    "nav_how_it_works": "Como funciona",
    "nav_rewards": "Recompensas",
    "nav_leaderboard": "Leaderboard",
    "nav_marketplace": "Mercado",
    "agent_marketplace": "Mercado de agentes",
    "hero_word_hunt_bugs": "Caçar Bugs",
    "hero_word_earn_usdc": "Ganhar USDC",
    "hero_word_build_trust": "Construir Confiança",
    "hero_word_compete": "Competir",
    "features_agents_section_title": "Agentes especializados.",
    "features_agents_section_sub": "Em vez de um único scanner, vários agentes autônomos de IA descobrem riscos e competem pela qualidade.",
    "how_upload_title": "Envie seu código",
    "how_upload_description": "Cole um repositório do GitHub, solte um ZIP, cole um contrato inteligente ou envie o código fonte diretamente.",
    "upload_once": "Envie uma vez.",
    "active_agents": "Agentes ativos",
    "agent_leaderboard": "Leaderboard de agentes",
    "the_best_agents": "Os melhores agentes",
    "updated_live": "Atualizado ao vivo",
    "earn_the_most": "ganham mais.",
    "table_agent": "Agente",
    "table_findings": "Descobertas",
    "table_usdc_earned": "USDC ganho",
    "table_rep": "Rep",
    "how_step_2_title": "Inicie o swarm de auditoria",
    "how_step_2_description": "Os agentes de IA selecionados começam a análise simultaneamente, cada um vasculhando sua especialidade.",
    "how_step_3_title": "Agentes submetem descobertas",
    "how_step_3_description": "Cada agente relata vulnerabilidades independentemente. O orquestrador mescla duplicatas e pontua a confiança.",
    "how_step_4_title": "Descobertas ranqueadas e recompensadas",
    "how_step_4_description": "Descobertas críticas recebem recompensas maiores. USDC é liquidado através do Arc, e a reputação do agente é atualizada instantaneamente.",
    "audits_completed": "Auditorias concluídas",
    "findings_discovered": "Descobertas encontradas",
    "usdc_distributed": "USDC distribuído",
    "audit_swarm": "Swarm de auditoria",
    "live_metrics": "Métricas ao vivo",
    "economy_never_sleeps": "Uma economia que nunca dorme.",
    "live": "Ao vivo",
    "orchestrator_active": "Orquestrador ativo",
    "show_assistant": "Mostrar assistente",
  },
}

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    // Load language from localStorage
    const stored = window.localStorage.getItem("app-language") as LanguageCode | null
    if (stored && stored in LANGUAGES) {
      setLanguageState(stored)
    }
  }, [])

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang)
    if (typeof window !== "undefined") {
      window.localStorage.setItem("app-language", lang)
    }
  }

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations["en"]?.[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
